version: "3.3"
services:

  broker:
    image: broker:latest
    build: broker
    environment:
      HOSTNAME: broker
    links:
      - BgkFranchise
      - McdFranchise
    ports:
      - 8080:8080
    restart: always

  McdFranchise:
    image: mcdfranchise:latest
    build: McdFranchise
    environment:
      HOSTNAME: McdFranchise
    links:
      - mcdJervis
      - mcdStillorgan
      - mcdTempleBar
    ports:
      - 8086:8086
    restart: always

  BgkFranchise:
    image: bgkfranchise:latest
    build: BgkFranchise
    environment:
      HOSTNAME: BgkFranchise
    links:
      - bgkBaggot
      - bgkGrafton
    ports:
      - 8087:8087
    restart: always

  mcdJervis:
    image: mcdjervis:latest
    build: mcdJervis
    restart: always

  mcdStillorgan:
    image: mcdstillorgan:latest
    build: mcdStillorgan
    restart: always

  mcdTempleBar:
    image: mcdtemplebar:latest
    build: mcdTempleBar
    restart: always

  bgkBaggot:
    image: bgkbaggot:latest
    build: bgkBaggot
    restart: always

  bgkGrafton:
    image: bgkgrafton:latest
    build: bgkGrafton
    restart: always